--- 
title: "Paramedics Feedback Analysis"
format: 
    dashboard:
        fontsize: 12
        logo: BSOLICB.png
        theme: cosmo
        scrolling: true
        expandable: true
        embed-resources: true        
execute:
    freeze: true
--- 

```{python}
#| output: false
#| echo: false
import pandas as pd
import os
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from nltk.stem.wordnet import WordNetLemmatizer
import re, string

nltk.download(['punkt',
              'stopwords',
              'wordnet',
               'omw-1.4',
              'averaged_perceptron_tagger'])
```

```{python}
os.chdir('//mlcsu-bi-fs/csugroupdata$/Commissioning Intelligence And Strategy/BSOLCCG/Reports/01_Adhoc/BSOL_1298_Paramedics_Feedback_Analysis')

data = pd.read_excel('Data\Feedback from Paramedics on the Road.xlsx', sheet_name='Data')
theme = pd.read_excel('Data\SurveyTheme.xlsx')

subset = data.loc[:, ['How easy is it to access a GP via the Non-Public number?',
                     'What services do you need to support you with admission avoidance to ED?',
                     'How likely are you to recommend OPAL+ to a colleague?',
                     'Have you used Patient Services on DoS?',
                     'Do Senior Clinicians come out to the Ambulance to discuss your patient when delayed?',
                     'Who do you call for Clinical Support on scene?',
                     'What do you feel would improve handover delays?',
                    'Have you used SDEC Services?'
                     ]]
```

```{python}
# Function to lemmatize words
def remove_noise_and_lemmatize(tokens, stop_words = ()):
    lemmatizer = WordNetLemmatizer()
    cleaned_tokens = []

    for token, tag in pos_tag(tokens):
        # Remove URLs
        token = re.sub('http[s]?://\S+', '', token)
        # Remove mentions
        token = re.sub('@\w+', '', token)
        # Remove punctuation including single quotes
        token = token.translate(str.maketrans('', '', string.punctuation + "'"))

        # Determine the part of speech tag
        if tag.startswith("NN"):
            pos = 'n'
        elif tag.startswith('VB'):
            pos = 'v'
        else:
            pos = 'a'

        # Lemmatize the token
        lemmatized_token = lemmatizer.lemmatize(token, pos)

        # Add token to cleaned tokens if it is not a stop word or empty
        if lemmatized_token not in stop_words and lemmatized_token not in string.punctuation and len(lemmatized_token) > 0:
            cleaned_tokens.append(lemmatized_token.lower())

    return cleaned_tokens

# Function to clean text
def clean_text(text):
    # Tokenize text
    tokens = word_tokenize(str(text).lower())

    # Apply noise removal and lemmatization
    cleaned_tokens = remove_noise_and_lemmatize(tokens, stopwords.words('english'))

    return ' '.join(cleaned_tokens)


# Function to Tokenize Text in Each Cell
def tokenize_responses(column):
    # Apply clean_text, which now includes tokenization and lemmatization
    cleaned_responses = column.apply(clean_text)

    # Split into individual words
    flat_list = [word for response in cleaned_responses for word in response.split()]

    # Create a new DataFrame with one word per row
    return pd.DataFrame(flat_list, columns=['Words'])

```

```{python}

# Create DataFrames for Each Question
Q1_df = tokenize_responses(subset['How easy is it to access a GP via the Non-Public number?'])
Q2_df = tokenize_responses(subset['What services do you need to support you with admission avoidance to ED?'])
Q3_df = tokenize_responses(subset['How likely are you to recommend OPAL+ to a colleague?'])
Q4_df = tokenize_responses(subset['Have you used Patient Services on DoS?'])
Q5_df = tokenize_responses(subset['Do Senior Clinicians come out to the Ambulance to discuss your patient when delayed?'])
Q6_df = tokenize_responses(subset['Who do you call for Clinical Support on scene?'])
Q7_df = tokenize_responses(subset['What do you feel would improve handover delays?'])
Q8_df = tokenize_responses(subset['Have you used SDEC Services?'])
```

```{python}
# Function to calculate word frequency
def word_frequency(data, column):
    word_counts = data[column].value_counts()
    word_counts_df = word_counts.reset_index()
    word_counts_df.columns = ['Word', 'Frequency']
    
    return word_counts_df

Q1_word_counts = word_frequency(Q1_df, 'Words')
Q2_word_counts = word_frequency(Q2_df, 'Words')
Q3_word_counts = word_frequency(Q3_df, 'Words')
Q4_word_counts = word_frequency(Q4_df, 'Words')
Q5_word_counts = word_frequency(Q5_df, 'Words')
Q6_word_counts = word_frequency(Q6_df, 'Words')
Q7_word_counts = word_frequency(Q7_df, 'Words')
Q8_word_counts = word_frequency(Q8_df, 'Words')
```

```{python}
#| echo: false
#| label: functions

#1. Function to plot word frequency 
import plotly.graph_objects as go

def plot_word_frequency(word_counts_df, plot_width=800, plot_height=600):
    # Sort the DataFrame by frequency in descending order
    sorted_df = word_counts_df.sort_values(by='Frequency', ascending=False)

    # Create a horizontal bar chart
    fig = go.Figure([go.Bar(x=sorted_df['Frequency'], y=sorted_df['Word'], orientation='h')])

    # Add titles and labels
    fig.update_layout(
        title='Word Frequency Distribution',
        xaxis_title='Frequency',
        yaxis_title='Words',
        yaxis=dict(autorange="reversed"),  # To display highest frequencies at the top
        width=plot_width,  # Width of the plot
        height=plot_height  # Height of the plot
    )

    # Show the plot
    fig.show()


#2. Function to plot bar chart

import plotly.express as px

## Horizontal bar chart

def plot_bar_chart(data, column, title):
    
    value_counts = data[column].value_counts().reset_index()
    value_counts.columns = ['Responses', 'Frequency']
    sorted_df = value_counts.sort_values(by='Frequency', ascending=False)
    
    fig = px.bar(sorted_df, x='Frequency', y='Responses', title=title, text = "Frequency", color="Frequency",
    color_continuous_scale=px.colors.sequential.Viridis)
    fig.update_traces(textposition="outside", textangle=0, cliponaxis=False)
    fig.update_layout(
        yaxis={'categoryorder':'total ascending'},
        showlegend=False,
        coloraxis_showscale=False
        #width=plot_width,  # Width of the plot
        #height=plot_height  # Height of the plot
    )
    fig.show()

## Vertical bar chart

def plot_bar_chart2(data, column, title):
    value_counts = data[column].value_counts().reset_index()
    value_counts.columns = ['Responses', 'Frequency']
    sorted_df = value_counts.sort_values(by='Frequency', ascending=False)
    
    fig = px.bar(sorted_df, x='Responses', y="Frequency", title=title,
    text = "Frequency", color="Frequency", color_continuous_scale=px.colors.sequential.Cividis_r)
    fig.update_traces(textposition="outside" , textangle=0, cliponaxis=False)
    fig.update_layout(
        yaxis={'categoryorder': 'total ascending'},
        xaxis_tickangle=-45,  # Setting the tick angle for the x-axis
        showlegend=False,
        coloraxis_showscale=False
        # width=plot_width,  # Width of the plot
        # height=plot_height  # Height of the plot
    )
    fig.show()
    
#3. Function to plot word cloud

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def plot_wordcloud(word_counts_data):
    
    # Create a dictionary where keys are words and values are their corresponding frequencies
    word_freq_dict = word_counts_data.set_index('Word')['Frequency'].to_dict()
    
    # Create a WordCloud object
    wordcloud = WordCloud(width=800, height=600, background_color ='white')

    # Generate a word cloud
    wordcloud.generate_from_frequencies(word_freq_dict)

    # Display the word cloud using matplotlib
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')  # Turn off axis numbers and labels
    plt.show()
      
```
# Background 

::: {.card title="Purpose" fill="false"}

This analysis delves into the textual feedback provided by paramedic crews, focusing on their perspectives and suggestions regarding various aspects of ambulance services. It encompasses their views on several topics, including:

1. The ease of accessing GPs through non-public numbers
2. The support services needed to avoid unnecessary admissions to Emergency Departments (EDs)
3. The likelihood of recommending OPAL+ to colleagues
4. Their experiences with Patient Services on DoS
5. The involvement of Senior Clinicians in on-scene discussions
6. The choices for clinical support during incidents
7. Ideas for reducing handover delays
8. The use of Same Day Emergency Care (SDEC) Services"

:::

::: {.card title="Methodology" fill="false"}
1. The responses were categorized into several common themes for a high-level analysis of feedback from paramedic crews and to facilitate visualization. Details of the categorization process are available in the data tab.
2. The most frequently used words were identified by splitting the responses into root words, following the removal of stop words, punctuation, and noise, and applying lemmatization using natural language processing techniques. Care must be taken when analyzing the frequency of words to consider the context in which they appear. Therefore, this word frequency analysis should be viewed in conjunction with the common themes identified in the respondents' answers.
:::

::: {.card title="Lead Analyst" fill="false"}
Siti Hassan <br>

If you have any suggestions or feedback, please forward them to this email: siti.hassan@nhs.net
:::

# User Guidance

::: {.card title="How to Interact with the Visuals" fill=false}

1. *Zooming*: Click and drag to select a specific area of the chart to zoom into for a closer look. Double-click to zoom back out.
2. *Panning*: Click on the pan button (it looks like a hand or a cross with arrows) in the graph's toolbar, then click and drag to move around the graph.
3. *Hover*: Move your mouse pointer over the bars to see additional information such as exact values or categories. A small tooltip will appear with the data.
4. *Resizing*: You can also click on the corners or edges of the graph to resize it within the window.
5. *Toolbar*: The toolbar, usually found at the top right of the graph, contains tools to manipulate the graph's view. Here's what each button does:
   - The camera icon allows you to download the graph.
   - The home icon resets the graph to its initial state.
   - The magnifying glass icons are for zooming in and out.
6. *Resetting the Graph*: If you've changed the graph view and want to return to the original view, click on the 'Home' button in the toolbar.

:::


::: {.card title="How to Interact with the Data Table" fill=false}

1. *Searching*: Use the 'Search' box to filter the table entries. As you type, the table will dynamically display only the rows that contain your search keyword.
2. *Sorting*: Click on any column header to sort the table by that column. Click once for ascending order, and click again for descending order.
3. *Changing Number of Entries Displayed*: You can change how many entries you view at a time by selecting a number from the 'Show [number] entries' dropdown menu, which typically appears above the table on the left-hand side.
4. *Copying, Excel, PDF*: Use the buttons located typically above the table on the right-hand side to copy data to the clipboard, export the table to an Excel file, or save the table as a PDF.

:::


# Q1 {orientation="columns" fill="false"}

## {.sidebar}

**Summary**:

1. The most frequent response indicated that accessing a GP via the Non-Public number is "Easy," which suggests a generally positive experience for the majority of respondents.

2. This is followed by reports of service inconsistency, as reflected in the "Hit and miss" responses.

3. A number of respondents expressed that it "Takes too long" to access a GP via the Non-Public number, highlighting issues related to delays.

4. Responses such as "Process does not work," "Numbers usually don't work," and "Don't answer the phone" point to significant difficulties and functionality issues within the service.

5. Three respondents mentioned that access success depended on the practice, with some needing to call back on the practice's regular number and wait in the queue, thus indicating that not all practices have Non-Public numbers.

## Column {width="60%" fill="true"}

```{python}
#| title: How easy is it to access a GP via the Non-Public number?
Q1_theme = pd.DataFrame(theme.iloc[:, 0].dropna())

plot_bar_chart2(Q1_theme, column = 'Q1.Theme', title = "" )

```

## Column {width="40%" fill="true"}

```{python}
#| title: The Most Frequent Words
plot_wordcloud(Q1_word_counts)
```

# Q2 {orientation="columns" fill="false"}

## {.sidebar}

**Summary**:

1. *Improved Out-of-Hours and Overnight Services*: Needs for more services outside normal GP hours, including out-of-hours GPs, district nurses, and extended hours for services like OPAL or SDEC.

2. *More Specialised Services and Direct Acess*: Suggestions include direct access to services like SDEC, SAU, MAU, ENT, urology, and pediatric advice for under 1s, without the need to go through EDs. 

3. *Streamlined Referral Processes and Single Point of Contact*: Having a single point of access for various services like OPAL, community, 111, & mental health or a simplified referral process to reduce confusion and enhance efficiency. 

4. *Mental Health Services*: Emphasizes the need for enhanced mental health services, including 24/7 mental health triage and direct access to mental health support without intermediary services. 

5. *Increased Acceptance of Referrals and Expanded Criteria*: Calls for broader acceptance of referrals to specialized units and less rejection of non-critical cases to ED. 

6. *Community and Home-Based Care*: Suggestions for more community-based services, night-sitting, increased capacity in community hospitals, and more in-home care options to reduce ED admissions. 

7. *Digital and Updated Directories of Services*: The need for a digital, constantly updated directory of services, possibly with a system that suggests the best service options based on input criteria.

8. *Funding and Resources for Bed Availability*: Addressing the issue of bed shortages and funding for more in-patient care facilities.

9. *Improved Patient Education and Public Awareness*: Emphasizing the need for educating the public on when to use emergency services and the availability of alternatives.

10. *Enhanced Skills and Capabilities for Paramedics*:  Emphasizes the need for expanding the scope of practice for paramedics, including the ability to perform more advanced medical procedures and to prescribe medications.

11. *Enhanced Support for Social Issues*: It emphasizes the need for better support mechanisms for patients who have social care needs rather than medical emergencies.

12. *Enhanced Support for Specific Conditions*: This includes pathways for conditions like TIA (Transient Ischemic Attack), chest pain clinics, early pregnancy issues, and catheter problems.

13. *Improved Clinical Decision Making*: Highlights the need for more effective consultation with experienced clinicians to determine the most appropriate level of care required, and subsequently, to facilitate referrals to alternative, possibly less intensive services when appropriate. 

14. *Improving Pre-Hospital Care and Discharge Processes*: The response questions why patients can't be treated and discharged directly from an ambulance when appropriate and calls for more support for patients with social issues who are medically fit but cannot be left at home.

## Column {width="60%" fill="false"}

```{python}
#| title: What services do you need to support you with admission avoidance to ED?
Q2_theme = pd.DataFrame(theme.iloc[:, 1].dropna())

plot_bar_chart(Q2_theme, column = 'Q2.Theme', title = "")
```


## Column {width="40%" fill="false"}

```{python}
#| title: The Most Frequent Words
plot_wordcloud(Q2_word_counts)
```

# Q3 to Q5

## Row {height=51% fill="false"}

```{python}
#| title: How likely are you to recommend OPAL+ to a colleague?


Q3 = pd.DataFrame(subset.iloc[:, 2])

plot_bar_chart2(Q3, column = 'How likely are you to recommend OPAL+ to a colleague?', title = "")

```

## Row {height=49% fill="false"}

```{python}
#| title: Have you used Patient Services on DoS?

Q4 = pd.DataFrame(subset.iloc[:, 3])

plot_bar_chart2(Q4, column = 'Have you used Patient Services on DoS?', title = "")
```


```{python}
#| title: Do Senior Clinicians come out to the Ambulance to discuss your patient when delayed?

Q5 = pd.DataFrame(subset.iloc[:, 4])

plot_bar_chart2(Q5, column = 'Do Senior Clinicians come out to the Ambulance to discuss your patient when delayed?', title = "")

```

# Q6 {orientation="columns" fill="false"}

## {.sidebar}

**Summary**:

1. *Referral to Specific Services*: Referral to specific services based on the patient's needs, including various specialized healthcare services.

2. *General Practitioner (GP)*: Many respondents mentioned calling a GP for clinical support on scene. 

3. *Depends on the Case*: Several responses highlight that the decision on whom to call is dependent on the particular situation at hand. These include calling direct wards, district nurses, or other relevant agencies.


## Column {width="55%" fill="false"}

```{python}
#| title: Who do you call for Clinical Support on scene?
Q6_theme = pd.DataFrame(theme.iloc[:, 2].dropna())

plot_bar_chart2(Q6_theme, column = 'Q6.Theme', title = "" )
```

## Column {width="45%" fill="false"}

```{python}
#| title: The Most Frequent Words
plot_wordcloud(Q6_word_counts)
```

# Q7 {orientation="columns" fill="false"}

## {.sidebar}

**Summary**:

1. *Enhanced Pre-Hospital Capabilities*: Some respondents suggest allowing ambulance clinicians to perform more diagnostic tests (like blood tests) on scene to streamline the patient journey and reduce delays upon arrival at the hospital.

2. *Streamlining Hospital Admissions and Discharges*: Responses suggest enhancing hospital discharge processes, especially during weekends, and considering alternative locations for waiting patients, like interim discharge wards.

3. *Improved Triage and Assessment Processes*: Many responses highlight the need for better triage systems, both in ambulance services and at hospitals, to ensure that patients are directed to the most appropriate care setting. This includes immediate triage by senior clinicians and better assessment on 111 calls.

4. *Extended Hours and Availability of Alternative Pathways*: Several responses suggest extending the operational hours of alternative healthcare pathways and services, such as Same Day Emergency Care (SDEC), Minor Injuries Units, and Out-of-Hours services, to reduce the reliance on emergency departments.

5. *Hospital and ED Operational Changes*: Responses indicate a need for hospitals to take more responsibility in managing handovers, such as providing cohort nurses, using corridors for patient care, and improving internal hospital processes to expedite patient flow.

6. *Direct Acess to Specialised Services*:Suggestions on having direct access to specialised services including MAU, SAU, pathways for TIA and  non cardiac chest pain.

7. *Increased Social and Community Care Support*: A few responses point to the need for more social care and community support to increase discharge rates from hospitals, thereby freeing up space and reducing handover delays.

8. *Improved Coordination and Communication*: Emphasizing the need for better communication between ambulance services and hospital staff, and more effective coordination of care, including the use of technology for handover processes.

9. *Optimizing Resource Utilization and Alternative Transportation*. Highlighting the importance of using resources efficiently by employing alternative transportation methods, such as taxis, for cases where ambulance services are not critically needed. This approach aims to ensure that ambulance services are reserved for more urgent and serious medical situations, while still providing a means for individuals to reach emergency departments when necessary.

10. *Public Education and Awareness*: Emphasis on educating the public about when to attend A&E, the availability of GP services, and the existence of alternative pathways. This includes suggestions for national advertising campaigns to inform the public about the appropriate use of healthcare services.

11. *Increased Acceptance of Referrals and Expanded Criteria*: Calls for broader acceptance of referrals to specialized units and less rejection of non-critical cases to ED. 

12. *Funding and Resources for Bed Availability*:  Addressing the issue of bed shortages and funding for more in-patient care facilities.

13. *Enhanced Skills and Capabilities for Paramedics*: Emphasizes the need for expanding the scope of practice for paramedics, including the ability to perform more advanced medical procedures and to prescribe medications.

14. *Political and Systemic Changes*: Some respondents mention the need for political action and prioritization, implying that the issue of handover delays requires systemic changes at a higher level.

15. *Welfare Support or Crews*: Calls for welfare support for crews who are typically stuck outside ED for hours.

16. *Walk-in Centre Drop-in Availability*: Suggestions on having walk-in drop-in availability.

17. *Preventative Care and Early Intervention*. Emphasizing the importance of primary care providers, such as General Practitioners (GPs), in preventing conditions from escalating to the point where hospitalization is necessary.

18. *Consistent and Standardized Pathways Across Services*: There's a call for more standardized and uniform pathways across different healthcare services to reduce confusion and inefficiency.

19. *Funding and Resources for Bed Availability*: Addressing the issue of bed shortages and funding for more in-patient care facilities.

20. *Staffing and Resource Enhancements*: Increasing staffing levels, especially during peak times, and improving resource allocation within hospitals and ambulance services.

## Column {width="60%" fill="false"}

```{python}
#| title: What do you feel would improve handover delays?
Q7_theme = pd.DataFrame(theme.iloc[:, 3].dropna())

plot_bar_chart(Q7_theme, column = 'Q7.Theme', title = "" )
```
## Column {width="40%" fill="false"}

```{python}
#| title: The Most Frequent Words
plot_wordcloud(Q7_word_counts)
```

# Q8

## Row {height="60%" fill="false"}

```{python}
#| title: Have you used SDEC Services?
Q8_theme = pd.DataFrame(theme.iloc[:, 4].dropna())

plot_bar_chart2(Q8_theme, column = 'Q8.Theme', title = "")
```
## Row {height = "40%" fill="false"}

| Response Category | Description | Examples |
|------------|-----------------------------|-----------------------------------------|
| Yes | The majority of responses indicate that respondents have utilized SDEC services. |          |
| No  | Respondents have not utilized SDEC services.                                     |          |
| Tried but Unsuccessful | Respondents attempted to use SDEC services but were unsuccessful, often due to full capacity or service unavailability. | "I have tried to refer and they are either full or not accepting." <br> "Working on CVT, they are often rejected as no observations on the patient, especially surgical cases." <br> "I have tried to refer and they are either full or not accepting." |
| Conditional or Qualified Yes   | Respondents have used the service or attempted to use it, but faced inconsistent outcomes or challenges. | "Yes, however, normally unsuccessful and advised no beds. Advised normally only fit to sit spaces available, and this is often full as well. " <br> "Yes, but it can be difficult and inconsistent. In my opinion, SDEC is a waste of time, money, and space. For instance, Shrewsbury SDEC has 6 beds and a 'fit to sit' area but only accepts patients for 10 hours a day. If patients aren’t suitable for SDEC, they must go to A&E anyway—why not utilize those beds for additional majors, open 24 hours a day, and make the service worthwhile?" |
| Sometimes  | Respondents indicate occasional or situational use of SDEC Services.  |          |
| SDEC Not Available | Respondents have noted that SDEC services are not available in their area, such as Stoke.   |          |

# Data   {orientation="rows" fill="false"}

```{python}
allData = pd.read_excel('Data\AllData.xlsx')
from itables import show
show(allData, 
buttons = ['copy', 'excel', 'pdf'])
```

